//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_GRUPO2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.T_PRODUCTOFACTURACION = new HashSet<T_PRODUCTOFACTURACION>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO_PRODUCTO { get; set; }
        public string ESTADO_PRODUCTOS { get; set; }
        public int CANTIDAD_STOCK { get; set; }
        public int ID_TIPO_PRODUCTO { get; set; }
    
        public virtual ESTADO_PRODUCTO ESTADO_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PRODUCTOFACTURACION> T_PRODUCTOFACTURACION { get; set; }
    }
}
