//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_GRUPO2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ACCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ACCIONES()
        {
            this.T_ROL_OPERACION = new HashSet<T_ROL_OPERACION>();
        }
    
        public int ID_ACCIONES { get; set; }
        public string NOMBRE { get; set; }
        public int ID_T_CLIENTE { get; set; }
        public int ID_T_PRODUCTO { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int ID_T_FACTURACION { get; set; }
    
        public virtual T_CLIENTE T_CLIENTE { get; set; }
        public virtual T_TIPO_PRODUCTO T_TIPO_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ROL_OPERACION> T_ROL_OPERACION { get; set; }
    }
}
