//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_GRUPO2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ADMINISTRADOR
    {
        public int ID_ADMINISTRADOR { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string EMAIL { get; set; }
        public string ESTADO_USUARIO { get; set; }
        public Nullable<int> ID_TIPO_PRODUCTO { get; set; }
        public Nullable<int> ID_FACTURACION { get; set; }
    
        public virtual T_FACTURACION T_FACTURACION { get; set; }
        public virtual T_TIPO_PRODUCTO T_TIPO_PRODUCTO { get; set; }
        public virtual T_USUARIO T_USUARIO { get; set; }
    }
}
