//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_GRUPO2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CARGO_METODO_PAGO
    {
        public int ID_CARGO_METODO_PAGOS { get; set; }
        public decimal CARGO_TARJETAS { get; set; }
        public decimal CARGO_SINPE { get; set; }
        public decimal CARGO_EFECTIVO { get; set; }
    }
}
