//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_GRUPO2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FACTURACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_FACTURACION()
        {
            this.T_PRODUCTOFACTURACION = new HashSet<T_PRODUCTOFACTURACION>();
        }
    
        public int ID_FACTURACION { get; set; }
        public System.DateTime FECHA_COMPRA { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_METODO_PAGO { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int ID_CALCULO_SUBTOTAL { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO_PRODUCTO { get; set; }
        public int CANTIDAD_STOCK { get; set; }
        public int CANTIDAD_PRODUCTO { get; set; }
        public Nullable<double> MONTOTOTAL { get; set; }
    
        public virtual T_ADMINISTRADOR T_ADMINISTRADOR { get; set; }
        public virtual T_CLIENTE T_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PRODUCTOFACTURACION> T_PRODUCTOFACTURACION { get; set; }
    }
}
