//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_GRUPO2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_METODO_PAGO
    {
        public int ID_METODO_PAGO { get; set; }
        public decimal PAGO_EFECTIVO { get; set; }
        public decimal PAGO_TARJETA { get; set; }
        public decimal PAGO_SINPE { get; set; }
    }
}
