//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_GRUPO2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USUARIO
    {
        public int ID_USUARIOS { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string EMAIL { get; set; }
        public string TIPO_USUARIO { get; set; }
        public int ESTADO_USUARIO { get; set; }
        public string CLAVE { get; set; }
        public string CONFIRMARCLAVE { get; set; }
    
        public virtual T_ADMINISTRADOR T_ADMINISTRADOR { get; set; }
        public virtual T_TIPO_USUARIO T_TIPO_USUARIO { get; set; }
    }
}
